version: '3.7'

networks:
  veritas-net:

services:
  template-migration:
    image: 'veritas-template:v0.0.1'
    command: "migrate -s file:///home/pay/migrations up"
    restart: on-failure
    networks:
      - veritas-net
    depends_on:
      - 'mongo-db'
    environment:
      TEMPLATE_ENV: dev
      TEMPLATE_DATABASE_URI: mongodb://${TEMPLATE_MONGO_USER:-template}:${TEMPLATE_MONGO_USER:-w2rd3n}@mongo-db:27017/?authSource=admin
      TEMPLATE_DATABASE_NAME: ${TEMPLATE_DATABASE_NAME:-templateDB}
      TEMPLATE_LOG_LEVEL: debug

  template:
    image: 'veritas-template:v0.0.1'
    container_name: 'template'
    networks:
      - veritas-net
    ports:
      - "8180:${TEMPLATE_SERVER_PORT:-8080}"
    depends_on:
      - 'mongo-db'
    environment:
      TEMPLATE_ENV: dev
      TEMPLATE_SERVER_PORT: ${TEMPLATE_SERVER_PORT:-9000}
      TEMPLATE_DATABASE_URI: mongodb://${TEMPLATE_MONGO_USER:-template}:${TEMPLATE_MONGO_USER:-w2rd3n}@mongo-db:27017/?authSource=admin
      TEMPLATE_DATABASE_NAME: ${TEMPLATE_DATABASE_NAME:-templateDB}
      TEMPLATE_LOG_LEVEL: debug

  mongo-db:
    image: 'mongo:latest'
    container_name: 'mongo-db'
    networks:
      - veritas-net
    ports:
      - '27100:27017'
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${TEMPLATE_MONGO_USER:-template}
      MONGO_INITDB_ROOT_PASSWORD: ${TEMPLATE_MONGO_USER:-w2rd3n}
  
  
  redis-db:
    image: redis:latest
    container_name: 'redis-db'
    networks:
      - veritas-net
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
